### PR TITLE
fix: pip install should now install all required files

### PR DESCRIPTION
**Pull request by mAxYoLo01**

### CODE REVIEW

**Review by EdVraz — CHANGES_REQUESTED** [review]
Don't use lib exc it's beta only, also packages was like that before and the folder wasn't included

**Comment by mAxYoLo01** [comment]
You want me to revert the `LibraryException` fixes? 
Adding the MANIFEST file fixed the folder not being included, at least on my end.

**Comment by EdVraz** [comment]
> You want me to revert the `LibraryException` fixes? 
> Adding the MANIFEST file fixed the folder not being included, at least on my end.

Yeaj

The file didn't show up for me :+1:

**Comment by mAxYoLo01** [comment]
Ok reverted it, but why use an exception that doesn't exist? I can't test the ext since it crashes

**Comment by EdVraz** [comment]
> Ok reverted it, but why use an exception that doesn't exist? I can't test the ext since it crashes

The ext is built for stable, you have beta or unstable installed I assume?

**Comment by mAxYoLo01** [comment]
I have the latest beta version

**Pull request merged**
